### ISSUE TITLE
Request: Scheduler: Start Instances on Bot startup

### ISSUE THREAD

**Issue by ninelore** [Special-K-s-Flightsim-Bots/DCSServerBot#45]
We currently restart the host nightly to work around a unrelated windows bug, however that leaves us with no server running without manual intervention.

An option to ensure a server will be started when the bot starts would be really helpful

Thanks in advance

**Comment by karel26** [comment]
You have that. Look at the scheduler plugin.

**Comment by ninelore** [comment]
If [this](https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/blob/master/plugins/scheduler/README.md) is the right documentation I am failing to find it. 
Is this implied by the `schedule` by any chance? So far i only had something like following:
```yaml
instance3:
  action:
    method: restart
    shutdown: true
    mission_time: 480
    populated: true
```
